#!/usr/bin/env python3
import hashlib
import itertools
import json
import re
import time
import urllib.request
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CATEGORIES = ("ads", "trackers", "malware", "gambling", "adult", "social")
DOMAIN_RE = re.compile(r"^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$")
BAD_TOKENS = ("$", "/", "\\", "[", "]", "(", ")", "{", "}", ",", ";", ":", "!", "?")


def read_json(path):
    return json.loads(path.read_text(encoding="utf-8"))


def read_domain_file(path):
    if not path.exists():
        return set()

    domains = set()
    for raw in path.read_text(encoding="utf-8").splitlines():
        domain = normalize_domain(raw)
        if domain:
            domains.add(domain)
    return domains


def fetch_text(url):
    request = urllib.request.Request(
        url,
        headers={
            "User-Agent": "CryptSurf-DNS-Blocklists/1.0",
            "Accept": "text/plain,*/*",
        },
    )
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read().decode("utf-8", errors="ignore")


def normalize_domain(raw):
    line = raw.strip().lower()
    if not line or line.startswith(("#", "!", ";", "[")):
        return None

    if " #" in line:
        line = line.split(" #", 1)[0].strip()
    if "\t#" in line:
        line = line.split("\t#", 1)[0].strip()

    if line.startswith("@@"):
        return None

    if line.startswith("||"):
        line = line[2:]
    if line.startswith("|"):
        line = line[1:]
    if line.startswith("*."):
        line = line[2:]
    if line.startswith("."):
        line = line[1:]

    if "^" in line:
        line = line.split("^", 1)[0]

    parts = line.split()
    if len(parts) >= 2 and is_ip_like(parts[0]):
        line = parts[1]
    elif len(parts) == 1:
        line = parts[0]
    else:
        return None

    line = line.removeprefix("http://").removeprefix("https://")
    line = line.split("/", 1)[0]
    line = line.split(":", 1)[0]
    line = line.strip(" .")

    if any(token in line for token in BAD_TOKENS):
        return None
    if is_ip_like(line):
        return None
    if not DOMAIN_RE.match(line):
        return None

    return line


def is_ip_like(value):
    return bool(re.match(r"^(?:\d{1,3}\.){3}\d{1,3}$", value))


def parse_source(text):
    domains = set()
    for line in text.splitlines():
        domain = normalize_domain(line)
        if domain:
            domains.add(domain)
    return domains


def ensure_dirs():
    for path in (
        ROOT / "output" / "domains",
        ROOT / "output" / "unbound",
        ROOT / "output" / "rpz",
    ):
        path.mkdir(parents=True, exist_ok=True)


def write_domains(path, domains, header):
    body = "\n".join(sorted(domains))
    content = f"# {header}\n# Generated by CryptSurf DNS pipeline\n{body}\n"
    path.write_text(content, encoding="utf-8")


def write_unbound(path, domains, header):
    lines = [
        f"# {header}",
        "# Generated by CryptSurf DNS pipeline",
    ]
    lines.extend(f'local-zone: "{domain}" always_nxdomain' for domain in sorted(domains))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_rpz(path, domains, zone_name):
    serial = time.strftime("%Y%m%d%H")
    lines = [
        "$TTL 300",
        f"@ SOA localhost. admin.cryptsurf.net. ({serial} 300 300 300 300)",
        "@ NS localhost.",
    ]
    lines.extend(f"{domain} CNAME ." for domain in sorted(domains))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def profile_name(flags):
    all_enabled = all(flags[category] for category in CATEGORIES)
    return (
        f"all-{int(all_enabled)}_"
        f"ads-{int(flags['ads'])}_"
        f"trackers-{int(flags['trackers'])}_"
        f"malware-{int(flags['malware'])}_"
        f"gambling-{int(flags['gambling'])}_"
        f"adult-{int(flags['adult'])}_"
        f"social-{int(flags['social'])}"
    )


def sha256_domains(domains):
    digest = hashlib.sha256()
    for domain in sorted(domains):
        digest.update(domain.encode("utf-8"))
        digest.update(b"\n")
    return digest.hexdigest()


def build():
    ensure_dirs()

    sources = read_json(ROOT / "config" / "sources.json")
    allowlist = read_domain_file(ROOT / "cryptsurf" / "allowlist.txt")
    categories = {}
    metadata = {
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "categories": {},
        "profiles": {},
        "sources": sources,
    }

    for category in CATEGORIES:
        domains = set()
        for source in sources.get(category, []):
            text = fetch_text(source["url"])
            domains.update(parse_source(text))

        denylist = read_domain_file(ROOT / "cryptsurf" / f"denylist_{category}.txt")
        domains.update(denylist)
        domains.difference_update(allowlist)
        categories[category] = domains

        write_domains(
            ROOT / "output" / "domains" / f"{category}.txt",
            domains,
            f"CryptSurf {category} domains",
        )
        write_unbound(
            ROOT / "output" / "unbound" / f"{category}.conf",
            domains,
            f"CryptSurf {category} Unbound rules",
        )
        write_rpz(
            ROOT / "output" / "rpz" / f"{category}.zone",
            domains,
            f"cryptsurf-{category}",
        )
        metadata["categories"][category] = {
            "count": len(domains),
            "sha256": sha256_domains(domains),
        }

    all_domains = set().union(*categories.values())
    write_domains(ROOT / "output" / "domains" / "all.txt", all_domains, "CryptSurf all domains")
    write_unbound(ROOT / "output" / "unbound" / "all.conf", all_domains, "CryptSurf all Unbound rules")
    write_rpz(ROOT / "output" / "rpz" / "all.zone", all_domains, "cryptsurf-all")

    for values in itertools.product((False, True), repeat=len(CATEGORIES)):
        flags = dict(zip(CATEGORIES, values))
        name = profile_name(flags)
        selected_categories = [
            category for category, enabled in flags.items() if enabled
        ]
        profile_domains = set()
        for category in selected_categories:
            profile_domains.update(categories[category])

        metadata["profiles"][name] = {
            "categories": selected_categories,
            "count": len(profile_domains),
            "sha256": sha256_domains(profile_domains),
        }

    metadata["categories"]["all"] = {
        "count": len(all_domains),
        "sha256": sha256_domains(all_domains),
    }
    (ROOT / "output" / "metadata.json").write_text(
        json.dumps(metadata, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    (ROOT / "output" / "profiles.json").write_text(
        json.dumps(metadata["profiles"], indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    build()
